[package]
name = "nog-menu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nog-iced = { path = "../nog-iced" }
windows = { path = "../windows" }
raw-window-handle = "0.3.3"
fuzzy-matcher = "0.3.7"
