[package]
name = "rgb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
lua = ["mlua"]

[dependencies]
mlua = { version = "0.6.2", features = ["luajit", "vendored", "serialize"], optional = true }
