[package]
name = "nog-client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nog-protocol = { path = "../nog-protocol" }
serde_json = "1.0"
